# Generated by Django 5.0.2 on 2024-02-13 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('photo', models.ImageField(blank=True, upload_to='photos', verbose_name='Photo')),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Date published')),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
            },
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('text', models.TextField(verbose_name="Poem's text")),
                ('theme', models.CharField(blank=True, choices=[('love', 'Лъагъуныгъэ'), ('homeland', 'Хэку'), ('adiga', 'Адыгэ'), ('life', 'Гъащӏэ'), ('friendship', 'Ныбжьэгъугъэ'), ('nature', 'Щӏыуэпс'), ('kid', 'Сабий'), ('animal', 'Псэущхьэ'), ('seasons', 'Лъэхъэнэ'), ('war', 'Зауэ'), ('parents', 'Адэ-Анэ'), ('humor', 'Гушыӏэ')], max_length=100)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Date published')),
                ('updated_at', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.author', verbose_name='Author')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poems.theme', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Poem',
                'verbose_name_plural': 'Poems',
            },
        ),
    ]
