# Generated by Django 5.0.2 on 2024-02-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='title',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Title'),
        ),
    ]
