# Generated by Django 5.0.2 on 2024-02-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_alter_poem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='created_at',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='Date published'),
        ),
    ]
