# Generated by Django 5.0.2 on 2024-02-16 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0003_alter_poem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='poems.author', verbose_name='Author'),
        ),
    ]
