# Generated by Django 5.0.2 on 2025-05-04 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0005_poem_likes_alter_poem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPoem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_date', models.DateField(db_index=True, unique=True)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_dates', to='poems.poem')),
            ],
            options={
                'verbose_name': 'Featured Poem',
                'verbose_name_plural': 'Featured Poems',
                'ordering': ['-featured_date'],
            },
        ),
    ]
